config/routes.rb
Rails.application.routes.draw do
  resources :packages
  resources :repositories
  resources :github_orgs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/healthz', to: proc { [200, {}, ['']] }
end

app/models/repository.rb
require 'pry'

class Repository < ApplicationRecord
  has_many :packages
  belongs_to :github_org

  def run(k8s:, last_update:)
    # There is no Repository CRD so I think
    # we could ignore this event except, ...
    #
    # Let's mark the Repository as updated:
    if updated_at < last_update
      touch
      save!
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[ show edit update destroy ]

  # GET /repositories or /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1 or /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories or /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to repository_url(@repository), notice: "Repository was successfully created." }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1 or /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to repository_url(@repository), notice: "Repository was successfully updated." }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1 or /repositories/1.json
  def destroy
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url, notice: "Repository was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repository_params
      params.require(:repository).permit(:name, :github_org_id)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_with(model: repository) do |form| %>
  <% if repository.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
        <% repository.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :github_org_id, style: "display: block" %>
    <%= form.text_field :github_org_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/_repository.html.erb
<div id="<%= dom_id repository %>">
  <p>
    <strong>Name:</strong>
    <%= repository.name %>
  </p>

  <p>
    <strong>Github org:</strong>
    <%= repository.github_org_id %>
  </p>

</div>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Show this repository", @repository %> |
  <%= link_to "Back to repositories", repositories_path %>
</div>

app/views/repositories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Repositories</h1>

<div id="repositories">
  <% @repositories.each do |repository| %>
    <%= render repository %>
    <p>
      <%= link_to "Show this repository", repository %>
    </p>
  <% end %>
</div>

<%= link_to "New repository", new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Back to repositories", repositories_path %>
</div>

app/views/repositories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @repository %>

<div>
  <%= link_to "Edit this repository", edit_repository_path(@repository) %> |
  <%= link_to "Back to repositories", repositories_path %>

  <%= button_to "Destroy this repository", @repository, method: :delete %>
</div>