config/routes.rb
Rails.application.routes.draw do
  resources :packages
  resources :repositories
  resources :github_orgs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/healthz', to: proc { [200, {}, ['']] }
end

app/models/github_org.rb
require 'pry'
require './app/models/package'

class GithubOrg < ApplicationRecord
  has_many :repositories
  has_many :packages, through: :repositories

  def run(k8s:, last_update:)
    t = last_update
    n = 0
    c = 0

    loop do
      # puts "###########Doing health check############"
      c = Package.where('updated_at > ?', t).count

      # Assume we get here within 5s (no, it's not really safe)
      break if c == package_count || n >= 7
      puts "########### fresh packages count: #{c} (expecting #{package_count}) #######"
      sleep 4
      n += 1
    end
    puts "########### final packages count: #{c} (expecting #{package_count}) #######"

    if c == package_count
      puts "########### cleaning up (OK!) #######"
      Measurement.do_measurement

      # Delete Sample project when we finished
      k8s.delete_project('fluxcd', 'default', {})
      touch
      save!
    else
      puts "########### c (#{c}) != package_count (#{package_count}) #######"
    end

    puts "########### this is the end of the GithubOrg#run Health Check method #######"
    # Watch all the Leaves, and when they
    # are ready, mark Project ready as well
  end
end

app/controllers/github_orgs_controller.rb
class GithubOrgsController < ApplicationController
  before_action :set_github_org, only: %i[ show edit update destroy ]

  # GET /github_orgs or /github_orgs.json
  def index
    @github_orgs = GithubOrg.all
  end

  # GET /github_orgs/1 or /github_orgs/1.json
  def show
  end

  # GET /github_orgs/new
  def new
    @github_org = GithubOrg.new
  end

  # GET /github_orgs/1/edit
  def edit
  end

  # POST /github_orgs or /github_orgs.json
  def create
    @github_org = GithubOrg.new(github_org_params)

    respond_to do |format|
      if @github_org.save
        format.html { redirect_to github_org_url(@github_org), notice: "Github org was successfully created." }
        format.json { render :show, status: :created, location: @github_org }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @github_org.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_orgs/1 or /github_orgs/1.json
  def update
    respond_to do |format|
      if @github_org.update(github_org_params)
        format.html { redirect_to github_org_url(@github_org), notice: "Github org was successfully updated." }
        format.json { render :show, status: :ok, location: @github_org }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @github_org.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_orgs/1 or /github_orgs/1.json
  def destroy
    @github_org.destroy

    respond_to do |format|
      format.html { redirect_to github_orgs_url, notice: "Github org was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_org
      @github_org = GithubOrg.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def github_org_params
      params.require(:github_org).permit(:name)
    end
end

app/helpers/github_orgs_helper.rb
module GithubOrgsHelper
end

app/views/github_orgs/_form.html.erb
<%= form_with(model: github_org) do |form| %>
  <% if github_org.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(github_org.errors.count, "error") %> prohibited this github_org from being saved:</h2>

      <ul>
        <% github_org.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/github_orgs/_github_org.html.erb
<div id="<%= dom_id github_org %>">
  <p>
    <strong>Name:</strong>
    <%= github_org.name %>
  </p>

</div>

app/views/github_orgs/edit.html.erb
<h1>Editing github org</h1>

<%= render "form", github_org: @github_org %>

<br>

<div>
  <%= link_to "Show this github org", @github_org %> |
  <%= link_to "Back to github orgs", github_orgs_path %>
</div>

app/views/github_orgs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Github orgs</h1>

<div id="github_orgs">
  <% @github_orgs.each do |github_org| %>
    <%= render github_org %>
    <p>
      <%= link_to "Show this github org", github_org %>
    </p>
  <% end %>
</div>

<%= link_to "New github org", new_github_org_path %>

app/views/github_orgs/new.html.erb
<h1>New github org</h1>

<%= render "form", github_org: @github_org %>

<br>

<div>
  <%= link_to "Back to github orgs", github_orgs_path %>
</div>

app/views/github_orgs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @github_org %>

<div>
  <%= link_to "Edit this github org", edit_github_org_path(@github_org) %> |
  <%= link_to "Back to github orgs", github_orgs_path %>

  <%= button_to "Destroy this github org", @github_org, method: :delete %>
</div>